FROM node:12 as builder

# Environment
ENV NODE_ENV production

RUN mkdir -p /usr/src/client
WORKDIR /usr/src/client
COPY package.json /usr/src/client
RUN yarn install
COPY . /usr/src/client

# RUN yarn global add serve
RUN yarn build

FROM nginx
COPY --from=builder /usr/src/client/nginx/default.conf /etc/nginx/conf.d/
COPY --from=builder /usr/src/client/build /usr/share/nginx/html

CMD /bin/sh -c "sed -i -e 's/HPORT/$PORT/g' /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
