sudo: required
language: node_js 
node_js: 
  - "12"
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PSWD" | docker login -u "$DOCKER_USER" --password-stdin
  - echo "$HEROKU_PSWD" | docker login -u "_" --password-stdin registry.heroku.com #logged in

script:
  - docker build -t $DOCKER_USER/smbr_client -f client/Dockerfile.client client;
  - docker tag $DOCKER_USER/smbr_client registry.heroku.com/$HEROKU_FRONT/web;
  - docker push $DOCKER_USER/smbr_client;
  - docker push registry.heroku.com/$HEROKU_FRONT/web;
  - heroku container:release web --app $HEROKU_FRONT;

  - docker build -t $DOCKER_USER/smbr_api -f api/Dockerfile.api api;
  - docker tag $DOCKER_USER/smbr_api registry.heroku.com/$HEROKU_BACK/web;
  - docker push $DOCKER_USER/smbr_api;
  - docker push registry.heroku.com/$HEROKU_BACK/web;
  - heroku container:release web --app $HEROKU_BACK;

  on: 
    branch: master 